services:
  mysql:
    image: mysql:8.0.32
    restart: always
    environment:
      MYSQL_DATABASE: Demo
      MYSQL_ROOT_PASSWORD: 12345
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql

  myapp:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
